spring:
   datasource:
      url: jdbc:sqlserver://walkingtree.database.windows.net:1433;database=wttdb;user=rootwtt@walkingtree;password=Root@wtt;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
      username: rootwtt
      password: Root@wtt
   jpa:
      show-sql: true
      hibernate:
         ddl-auto: update
        
         
server:
   port: 9191         
            
